#############################################################################
# Generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#  May 12, 2021 03:31:53 PM CST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {新宋体} -size 10"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1091x510+336+112
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 781
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Tkaligner"
    vTcl:DefineAlias "$top" "Aligner" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra43" "FramePad" vTcl:WidgetProc "Aligner" 1
    set site_3_0 $top.fra43
    ttk::style configure PC.TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure PC.TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style layout PC.TNotebook.Tab {
                    Notebook.tab -children {
                        Notebook.padding -side top -children {
                            Notebook.focus -side top -children {
                                Notebook.text -side right
                                Notebook.image -side left
                            }
                        }
                    }
               }
    vTcl::widgets::ttk::pnotebook::createCmd $site_3_0.pNo46 \
        -width 300 -height 200 -takefocus {} -style "PC.TNotebook" \
        -style PC.TNotebook 
    vTcl:DefineAlias "$site_3_0.pNo46" "PNotebook1" vTcl:WidgetProc "Aligner" 1
    $site_3_0.pNo46 configure -style "PC.TNotebook"
    bind $site_3_0.pNo46 <Button-1> {
        _button_press
    }
    bind $site_3_0.pNo46 <ButtonRelease-1> {
        _button_release
    }
    bind $site_3_0.pNo46 <Motion> {
        _mouse_over
    }
    frame $site_3_0.pNo46.t0 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.pNo46.t0" "PNotebook1_t1" vTcl:WidgetProc "Aligner" 1
    $site_3_0.pNo46 add $site_3_0.pNo46.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image image2 \
        -compound left -underline -1 
    set site_5_0  $site_3_0.pNo46.t0
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu50 \
        -takefocus {} -text Tbutton 
    vTcl:DefineAlias "$site_5_0.tBu50" "TButton1" vTcl:WidgetProc "Aligner" 1
    place $site_5_0.tBu50 \
        -in $site_5_0 -x 0 -relx 0.386 -y 0 -rely 0.306 -width 76 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.pNo46.t1 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.pNo46.t1" "PNotebook1_t2" vTcl:WidgetProc "Aligner" 1
    $site_3_0.pNo46 add $site_3_0.pNo46.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image image2 \
        -compound left -underline -1 
    set site_5_1  $site_3_0.pNo46.t1
    ttk::entry $site_5_1.tEn51 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_5_1.tEn51" "TEntry1" vTcl:WidgetProc "Aligner" 1
    place $site_5_1.tEn51 \
        -in $site_5_1 -x 0 -relx 0.35 -y 0 -rely 0.349 -width 0 \
        -relwidth 0.116 -height 0 -relheight 0.092 -anchor nw \
        -bordermode ignore 
    place $site_3_0.pNo46 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    menu $top.m47 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font $vTcl(actual_gui_font_menu_desc) \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $top.m47 add cascade \
        -menu "$top.m47.men48" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -font TkDefaultFont -foreground $vTcl(actual_gui_menu_fg) -label File 
    set site_3_0 $top.m47
    menu $site_3_0.men48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) \
        -font $vTcl(actual_gui_font_menu_desc) -foreground black -tearoff 0 
    $site_3_0.men48 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command {#open1_command} -font TkDefaultFont \
        -foreground $vTcl(actual_gui_menu_fg) -label Open1 -underline 0 
    $site_3_0.men48 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command {#open2_command} -font TkDefaultFont \
        -foreground $vTcl(actual_gui_menu_fg) -label Open2 -underline 1 
    $site_3_0.men48 add separator \
        -background $vTcl(actual_gui_bg) 
    $site_3_0.men48 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command {#savetsv_command} -font TkDefaultFont \
        -foreground $vTcl(actual_gui_menu_fg) -label SaveCsv -underline 4 
    $site_3_0.men48 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command {#savetmx_command} -font TkDefaultFont \
        -foreground $vTcl(actual_gui_menu_fg) -label SaveTMX -underline 5 
    $site_3_0.men48 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command {#savexlsx_command} -font {-family {Segoe UI} -size 9} \
        -foreground $vTcl(actual_gui_menu_fg) -label SaveXlsx -underline 7 
    $site_3_0.men48 add separator \
        -background $vTcl(actual_gui_bg) 
    $site_3_0.men48 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -command {#quit_command} -font TkDefaultFont \
        -foreground $vTcl(actual_gui_menu_fg) -label Quit -underline 0 
    $top.m47 add cascade \
        -menu "$top.m47.men49" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -font TkDefaultFont -foreground $vTcl(actual_gui_menu_fg) -label Edit 
    set site_3_0 $top.m47
    menu $site_3_0.men49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) \
        -font $vTcl(actual_gui_font_menu_desc) -foreground black -tearoff 0 
    $site_3_0.men49 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -accelerator Ctrl+P \
        -background $vTcl(actual_gui_bg) -command {#palign_command} \
        -font TkDefaultFont -foreground $vTcl(actual_gui_menu_fg) \
        -label PAlign -underline 0 
    $site_3_0.men49 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -accelerator Ctrl+S \
        -background $vTcl(actual_gui_bg) -command {#salign_command} \
        -font TkDefaultFont -foreground $vTcl(actual_gui_menu_fg) \
        -label SAlign -underline 0 
    $site_3_0.men49 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -accelerator Ctrl+R \
        -background $vTcl(actual_gui_bg) -command {#reset_command} \
        -font TkDefaultFont -foreground $vTcl(actual_gui_menu_fg) \
        -label Reset -underline 0 
    $top.m47 add cascade \
        -menu "$top.m47.men50" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -font TkDefaultFont -foreground $vTcl(actual_gui_menu_fg) -label Help 
    set site_3_0 $top.m47
    menu $site_3_0.men50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) \
        -font $vTcl(actual_gui_font_menu_desc) -foreground black -tearoff 0 
    $site_3_0.men50 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -accelerator Ctrl+H \
        -background $vTcl(actual_gui_bg) -command {#on_howto} \
        -font TkDefaultFont -foreground $vTcl(actual_gui_menu_fg) \
        -label Howto -underline 0 
    $site_3_0.men50 add command \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -accelerator Ctrl-I \
        -background $vTcl(actual_gui_bg) -command {#on_about} \
        -font TkDefaultFont -foreground $vTcl(actual_gui_menu_fg) \
        -label About -underline 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 0.5 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

